import texts
e = {'branch', 'nation', 'desert', 'ground', 'island', 'cookie', 'hunger', 'pillow', 'flower', 'police', 'tomato', 'cruise', 'driver', 'cheese', 'circus', 'meadow', 'parent', 'carrot', 'friend', 'canyon', 'hollow', 'pencil', 'banana', 'insect', 'laptop', 'turtle', 'hazard', 'pocket', 'number', 'puzzle', 'career', 'health', 'garden', 'candle', 'engine', 'banner', 'credit', 'lizard', 'master', 'leader', 'flight', 'mosaic', 'inmate', 'guitar', 'praise', 'empire', 'doctor', 'holler', 'planet', 'motion', 'carbon', 'family', 'castle', 'picnic', 'person', 'nature', 'energy', 'common', 'mirror', 'legend', 'hammer', 'potato', 'window', 'camera', 'lumber', 'genius', 'canvas', 'beetle', 'school', 'crater', 'bullet', 'goblin', 'powder', 'golden', 'lagoon', 'ladder', 'silver', 'paddle', 'cereal', 'dragon', 'button', 'change', 'zipper', 'forest', 'debate', 'profit', 'bright', 'chance', 'handle', 'prince', 'jigsaw', 'impact', 'bottle', 'coffee', 'cherry', 'import', 'oyster', 'kitten', 'column', 'market', 'jungle', 'collar', 'wallet', 'orange', 'cotton', 'rocket', 'gentle', 'burden', 'puddle', 'marble', 'divide', 'monkey', 'danger', 'magnet', 'puppet', 'patron', 'player', 'farmer'}
m = {'ballet', 'bubble', 'brandy', 'bonnet', 'basalt', 'cavern', 'belter', 'barrel', 'bunker', 'butter', 'brides', 'banter', 'burner', 'blazer', 'basket', 'beauty', 'bridge', 'carpet', 'cannon', 'beacon', 'barman', 'bender', 'bather', 'haggle', 'canter', 'broker', 'bakery', 'booger', 'braise', 'bronze', 'basset', 'trophy', 'bomber', 'bungle', 'buffer', 'burrow', 'browse', 'bucket', 'barber', 'bistro', 'cellar', 'ballot', 'bangle', 'hacker', 'battle', 'bridle', 'barrow', 'breath', 'bundle'}
h = {'chapel', 'drivel', 'embark', 'except', 'drover', 'devout', 'azalea', 'estate', 'zenith', 'whiffs', 'escape', 'anchor', 'future', 'detail', 'ascent', 'floral', 'gizmos', 'forbid', 'gloomy', 'cradle', 'faulty', 'advice', 'fringe', 'formal', 'gadget', 'evenly', 'custom', 'action', 'bishop', 'gazebo', 'quasar', 'beyond', 'gospel', 'figure', 'finite', 'corona', 'consul', 'fjords', 'cleric', 'budget', 'bridal', 'dormer', 'easter', 'agenda', 'zircon', 'duplex', 'glossy', 'either', 'artist', 'direct', 'forget', 'ginger', 'copper', 'fathom', 'glance', 'defect', 'comedy', 'depict', 'giggle', 'flinch', 'grieve', 'fright', 'agency', 'quorum', 'defeat', 'diesel', 'detect', 'cosmic', 'avenue', 'during', 'county', 'grumpy', 'buffet', 'gather', 'device', 'excess', 'dimmed', 'burger', 'bluish', 'creole', 'define', 'crewed', 'gossip', 'adjust', 'pyjama', 'dipper', 'format', 'effort', 'ethics', 'donate', 'accent', 'author', 'cousin', 'escort', 'bijoux', 'anthem', 'enable', 'fusion', 'dapper', 'foster', 'groove', 'gamble', 'course', 'desire', 'quiche', 'former', 'cuffed', 'famous', 'xylose', 'almost', 'quartz', 'design', 'employ', 'belong', 'falcon', 'decked', 'global', 'cringe', 'frenzy', 'earwig', 'garlic', 'cyclic', 'klaxon', 'effect', 'finale', 'clinic', 'divine', 'attire', 'bruise', 'dreary', 'crowed', 'extend', 'demand', 'fellow', 'beware', 'enlist', 'fervor', 'colony', 'archer', 'ensure', 'catchy', 'devise', 'expert', 'frozen', 'cinema', 'closet', 'gender', 'analog', 'grease', 'domain', 'female', 'decree', 'before', 'costly', 'earned', 'fought', 'driven', 'follow', 'facade', 'convoy', 'flumes', 'zephyr', 'aspect', 'coming', 'export'}

f = open("words.txt", 'r').readlines()
for i in f:
  if len(i.strip()) == 6 and i.strip() in texts.eng_play_words[6] and i.strip() not in e and i.strip() not in h:
    m.add(i.strip())
print(len(m), m)